REPORTES = [
    {
        "id": "RPT-001",
        "usuario": "Ana García",
        "fecha": "2025-04-05",
        "descripcion": "Bache profundo en Av. Insurgentes Sur frente al metro Mixcoac, peligroso para vehículos y ciclistas.",
        "categoria": "infraestructura",
        "tipo": "Bache vial",
        "prioridad": "alta",
        "probabilidad": 87,
        "lat": 19.3699,
        "lon": -99.1870,
        "status": "procesado",
        "capturas": 2,
    },
    {
        "id": "RPT-002",
        "usuario": "Carlos Méndez",
        "fecha": "2025-04-04",
        "descripcion": "Luminaria apagada en Calle Amores 245, Colonia del Valle, inseguro en las noches.",
        "categoria": "infraestructura",
        "tipo": "Alumbrado público",
        "prioridad": "media",
        "probabilidad": 72,
        "lat": 19.3800,
        "lon": -99.1600,
        "status": "procesado",
        "capturas": 1,
    },
    {
        "id": "RPT-003",
        "usuario": "María Torres",
        "fecha": "2025-04-04",
        "descripcion": "Basura acumulada en parque Hundido desde hace 3 días, mal olor y riesgo sanitario.",
        "categoria": "medio_ambiente",
        "tipo": "Manejo de residuos",
        "prioridad": "media",
        "probabilidad": 65,
        "lat": 19.3752,
        "lon": -99.1814,
        "status": "procesado",
        "capturas": 3,
    },
    {
        "id": "RPT-004",
        "usuario": "Luis Ramírez",
        "fecha": "2025-04-03",
        "descripcion": "Fuga de agua visible en banqueta de Insurgentes y Félix Cuevas, lleva más de una semana.",
        "categoria": "servicios",
        "tipo": "Fuga de agua",
        "prioridad": "alta",
        "probabilidad": 91,
        "lat": 19.3821,
        "lon": -99.1765,
        "status": "procesado",
        "capturas": 1,
    },
    {
        "id": "RPT-005",
        "usuario": "Rosa Hernández",
        "fecha": "2025-04-02",
        "descripcion": "Árbol caído parcialmente bloqueando la calle Parroquia, solo un carril libre.",
        "categoria": "areas_verdes",
        "tipo": "Arborización",
        "prioridad": "baja",
        "probabilidad": 54,
        "lat": 19.3672,
        "lon": -99.1698,
        "status": "procesado",
        "capturas": 0,
    },
    # ── Reportes pendientes (aún no analizados por IA) ──────────────────────
    {
        "id": "RPT-006",
        "usuario": "Ana García",
        "fecha": "2025-04-08",
        "descripcion": "Semáforo descompuesto en Insurgentes y Mixcoac, solo parpadea en amarillo.",
        "categoria": "infraestructura",
        "tipo": "—",
        "prioridad": "pendiente",
        "probabilidad": 0,
        "lat": 19.3714,
        "lon": -99.1856,
        "status": "pendiente",
        "capturas": 2,
    },
    {
        "id": "RPT-007",
        "usuario": "Ana García",
        "fecha": "2025-04-08",
        "descripcion": "Grafiti en muro del parque Tlacoquemécatl, frente a la entrada principal.",
        "categoria": "servicios",
        "tipo": "—",
        "prioridad": "pendiente",
        "probabilidad": 0,
        "lat": 19.3641,
        "lon": -99.1712,
        "status": "pendiente",
        "capturas": 1,
    },
]

CATEGORIAS = {
    "infraestructura": {"label": "Infraestructura",    "badge": "badge-info"},
    "seguridad":       {"label": "Seguridad",           "badge": "badge-alta"},
    "areas_verdes":    {"label": "Áreas verdes",        "badge": "badge-baja"},
    "servicios":       {"label": "Servicios públicos",  "badge": "badge-media"},
    "transporte":      {"label": "Transporte",          "badge": "badge-info"},
    "medio_ambiente":  {"label": "Medio ambiente",      "badge": "badge-baja"},
}